<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <link name="lidar_link">
            <visual>
                <geometry>
                    <cylinder radius="0.1" length="0.05" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.1" length="0.05" />
                </geometry>
                    <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="0.1" r="0.1" h="0.05" 
                                        xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="lidar_sensor" />

    <joint name="lidar_joint" type="fixed" >
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="0 0 ${base_height+0.05/2}" rpy="0 0 0" />
    </joint>

    <joint name="lidar_sensor_joint" type="fixed" >
        <parent link="lidar_link" />
        <child link="lidar_sensor" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <gazebo reference="lidar_sensor">
        <sensor type="ray" name="lidar">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <always_on>true</always_on>
            <update_rate>15</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.15</min>
                    <max>1.5</max>
                    <resolution>0.017453</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="laser_plugin" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>lidar_sensor</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>
