controller_manager:
  ros__parameters:
    update_rate: 100 #Hz
    scorbot_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scorbot_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: false
    
    interpolation_method: splines

    gains:
      joint_1:
        p: 21.0
        i: 0.21
        d: 2.1
      joint_2:
        p: 21.0
        i: 0.21
        d: 2.1
      joint_3:
        p: 21.0
        i: 0.21
        d: 2.1
      joint_4:
        p: 21.0
        i: 0.21
        d: 2.1

    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.01
      joint_1:
        trajectory: 0.2  
        goal: 0.15       
      joint_2:
        trajectory: 0.2  
        goal: 0.15       
      joint_3:
        trajectory: 0.2
        goal: 0.15
      joint_4:
        trajectory: 0.2
        goal: 0.15
